SELECT
          SDF.DEFINITION_NAME,

          DEP.PERIOD_CODE,
          MDS.OBSERVATION_DATE,

          OBS.OBSERVATION_VALUE,

          CALL_PUT_INDICATOR_CODE.name AS CALL_PUT_INDICATOR,
          STRIKE_PRICE
     FROM MDOWNERBS1.MDOBS_OBSERVATION OBS
          INNER JOIN MDOWNERBS1.MDOBP_OBSERVATION_PERIOD OBP
             ON OBS.OBSERVATION_PERIOD_MDOBP_FK = OBP.MDOBP_PK
          INNER JOIN MDOWNERBS1.MDMDS_MARKET_DATA_SERIES MDS
             ON MDS.MDMDS_PK = OBP.MARKET_DATA_SERIES_MDMDS_FK
          LEFT OUTER JOIN RDOWNERBS1.RDSDF_SERIES_DEF SDF
             ON MDS.SERIES_DEFINITION_GI = SDF.RDSDF_GI
          LEFT OUTER JOIN RDOWNERBS1.RDDEP_DELIVERY_PERIOD DEP
             ON OBP.DELIVERY_PERIOD_GI = DEP.RDDEP_GI
          LEFT OUTER JOIN RDOWNERBS1.RDOBT_OBSERVATION_TYPE OBT
             ON OBS.OBSERVATION_TYPE_GI = OBT.RDOBT_GI
          LEFT OUTER JOIN RDOWNERBS1.RDCOD_CODE OBS_STATUS_CODE
             ON OBS.OBSERVATION_STATUS_GI = OBS_STATUS_CODE.RDCOD_GI
          LEFT OUTER JOIN RDOWNERBS1.RDCOD_CODE OBS_OVERALL_STATUS_CODE
             ON OBS.OVERALL_OBS_STATUS_GI = OBS_OVERALL_STATUS_CODE.RDCOD_GI
          -- New columns
          LEFT OUTER JOIN RDOWNERBS1.rdogm_oil_guid_mapping CALL_PUT_INDICATOR_CODE ON OBS.CALL_PUT_INDICATOR_GI = CALL_PUT_INDICATOR_CODE.rdogm_gi

WHERE
  MDS.OBSERVATION_DATE>'20-MAY-2014'
  AND SDF.DEFINITION_NAME in ('ICE.BRENT', 'NYMEX.WTI', 'NYMEX.RBOB', 'NYMEX.HO', 'ICE.GASOIL', 'ICE BRENT O', 'NYMEX WTI O')
  AND OBT.NAME = 'S'
ORDER BY SDF.DEFINITION_NAME, DEP.PERIOD_CODE, OBSERVATION_DATE